#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
  systemctl daemon-reload
  deb-systemd-helper enable camera-coordinator-autolight.service
  systemctl start camera-coordinator-autolight.service
fi

exit 0
