// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package cameracoordinator

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type camera_detector_vb2_ioctlCameraEvent struct {
	_         structs.HostLayout
	EventType uint32
	Source    uint32
	Pid       uint32
	Name      [32]uint8
}

type camera_detector_vb2_ioctlDeviceNameKey struct {
	_    structs.HostLayout
	Name [32]uint8
}

// loadCamera_detector_vb2_ioctl returns the embedded CollectionSpec for camera_detector_vb2_ioctl.
func loadCamera_detector_vb2_ioctl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Camera_detector_vb2_ioctlBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load camera_detector_vb2_ioctl: %w", err)
	}

	return spec, err
}

// loadCamera_detector_vb2_ioctlObjects loads camera_detector_vb2_ioctl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*camera_detector_vb2_ioctlObjects
//	*camera_detector_vb2_ioctlPrograms
//	*camera_detector_vb2_ioctlMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCamera_detector_vb2_ioctlObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCamera_detector_vb2_ioctl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// camera_detector_vb2_ioctlSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type camera_detector_vb2_ioctlSpecs struct {
	camera_detector_vb2_ioctlProgramSpecs
	camera_detector_vb2_ioctlMapSpecs
	camera_detector_vb2_ioctlVariableSpecs
}

// camera_detector_vb2_ioctlProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type camera_detector_vb2_ioctlProgramSpecs struct {
	KprobeVb2FopRelease     *ebpf.ProgramSpec `ebpf:"kprobe_vb2_fop_release"`
	KprobeVb2IoctlStreamoff *ebpf.ProgramSpec `ebpf:"kprobe_vb2_ioctl_streamoff"`
	KprobeVb2IoctlStreamon  *ebpf.ProgramSpec `ebpf:"kprobe_vb2_ioctl_streamon"`
}

// camera_detector_vb2_ioctlMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type camera_detector_vb2_ioctlMapSpecs struct {
	CameraEventRingbuf *ebpf.MapSpec `ebpf:"camera_event_ringbuf"`
	StreamingPid       *ebpf.MapSpec `ebpf:"streaming_pid"`
}

// camera_detector_vb2_ioctlVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type camera_detector_vb2_ioctlVariableSpecs struct {
}

// camera_detector_vb2_ioctlObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCamera_detector_vb2_ioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type camera_detector_vb2_ioctlObjects struct {
	camera_detector_vb2_ioctlPrograms
	camera_detector_vb2_ioctlMaps
	camera_detector_vb2_ioctlVariables
}

func (o *camera_detector_vb2_ioctlObjects) Close() error {
	return _Camera_detector_vb2_ioctlClose(
		&o.camera_detector_vb2_ioctlPrograms,
		&o.camera_detector_vb2_ioctlMaps,
	)
}

// camera_detector_vb2_ioctlMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCamera_detector_vb2_ioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type camera_detector_vb2_ioctlMaps struct {
	CameraEventRingbuf *ebpf.Map `ebpf:"camera_event_ringbuf"`
	StreamingPid       *ebpf.Map `ebpf:"streaming_pid"`
}

func (m *camera_detector_vb2_ioctlMaps) Close() error {
	return _Camera_detector_vb2_ioctlClose(
		m.CameraEventRingbuf,
		m.StreamingPid,
	)
}

// camera_detector_vb2_ioctlVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCamera_detector_vb2_ioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type camera_detector_vb2_ioctlVariables struct {
}

// camera_detector_vb2_ioctlPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCamera_detector_vb2_ioctlObjects or ebpf.CollectionSpec.LoadAndAssign.
type camera_detector_vb2_ioctlPrograms struct {
	KprobeVb2FopRelease     *ebpf.Program `ebpf:"kprobe_vb2_fop_release"`
	KprobeVb2IoctlStreamoff *ebpf.Program `ebpf:"kprobe_vb2_ioctl_streamoff"`
	KprobeVb2IoctlStreamon  *ebpf.Program `ebpf:"kprobe_vb2_ioctl_streamon"`
}

func (p *camera_detector_vb2_ioctlPrograms) Close() error {
	return _Camera_detector_vb2_ioctlClose(
		p.KprobeVb2FopRelease,
		p.KprobeVb2IoctlStreamoff,
		p.KprobeVb2IoctlStreamon,
	)
}

func _Camera_detector_vb2_ioctlClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed camera_detector_vb2_ioctl_x86_bpfel.o
var _Camera_detector_vb2_ioctlBytes []byte
