// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cameracoordinator

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCameraDetector returns the embedded CollectionSpec for cameraDetector.
func loadCameraDetector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CameraDetectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cameraDetector: %w", err)
	}

	return spec, err
}

// loadCameraDetectorObjects loads cameraDetector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cameraDetectorObjects
//	*cameraDetectorPrograms
//	*cameraDetectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCameraDetectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCameraDetector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cameraDetectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cameraDetectorSpecs struct {
	cameraDetectorProgramSpecs
	cameraDetectorMapSpecs
	cameraDetectorVariableSpecs
}

// cameraDetectorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cameraDetectorProgramSpecs struct {
	KprobeVb2IoctlStreamoff *ebpf.ProgramSpec `ebpf:"kprobe_vb2_ioctl_streamoff"`
	KprobeVb2IoctlStreamon  *ebpf.ProgramSpec `ebpf:"kprobe_vb2_ioctl_streamon"`
}

// cameraDetectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cameraDetectorMapSpecs struct {
	CameraEvents *ebpf.MapSpec `ebpf:"camera_events"`
}

// cameraDetectorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cameraDetectorVariableSpecs struct {
}

// cameraDetectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCameraDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type cameraDetectorObjects struct {
	cameraDetectorPrograms
	cameraDetectorMaps
	cameraDetectorVariables
}

func (o *cameraDetectorObjects) Close() error {
	return _CameraDetectorClose(
		&o.cameraDetectorPrograms,
		&o.cameraDetectorMaps,
	)
}

// cameraDetectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCameraDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type cameraDetectorMaps struct {
	CameraEvents *ebpf.Map `ebpf:"camera_events"`
}

func (m *cameraDetectorMaps) Close() error {
	return _CameraDetectorClose(
		m.CameraEvents,
	)
}

// cameraDetectorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCameraDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type cameraDetectorVariables struct {
}

// cameraDetectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCameraDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type cameraDetectorPrograms struct {
	KprobeVb2IoctlStreamoff *ebpf.Program `ebpf:"kprobe_vb2_ioctl_streamoff"`
	KprobeVb2IoctlStreamon  *ebpf.Program `ebpf:"kprobe_vb2_ioctl_streamon"`
}

func (p *cameraDetectorPrograms) Close() error {
	return _CameraDetectorClose(
		p.KprobeVb2IoctlStreamoff,
		p.KprobeVb2IoctlStreamon,
	)
}

func _CameraDetectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cameradetector_x86_bpfel.o
var _CameraDetectorBytes []byte
